# exp_6650 公共训练调度；使用全部 6650 张图，不启用论文 train/test 划分。
NUM_IMAGES=${NUM_IMAGES:-6650}
EPOCHS=${EPOCHS:-100}
ITERATIONS=$((NUM_IMAGES * EPOCHS))
DENSIFY_INTERVAL=$((NUM_IMAGES / 3))
DENSIFY_FROM=$NUM_IMAGES
DENSIFY_UNTIL=$((NUM_IMAGES * 50))
OPACITY_RESET_INTERVAL=$((NUM_IMAGES * 15))
# 随训练总长度衰减，避免仍在 30000 次时提前降至最终学习率。
POSITION_LR_STEPS=${POSITION_LR_STEPS:-$ITERATIONS}

# 数据加载：并行读取，CUDA 相机对象在主线程创建。
CAMERA_LOAD_WORKERS=${CAMERA_LOAD_WORKERS:-8}
CAMERA_TORCH_THREADS=${CAMERA_TORCH_THREADS:-1}
MASK_SIGMA=${MASK_SIGMA:-0}  # 参考最终实验采用硬遮罩；7 恢复旧软遮罩

# 保留部署版本的语义、频率加权和多尺度 SSIM。
SEMANTIC_EQUIPMENT_WEIGHT=${SEMANTIC_EQUIPMENT_WEIGHT:-3.0}
SEMANTIC_BACKGROUND_WEIGHT=${SEMANTIC_BACKGROUND_WEIGHT:-0.5}
FREQ_WEIGHT_ALPHA=${FREQ_WEIGHT_ALPHA:-0.5}
# 参考公共实验未使用部署版的额外不透明度百分比剪枝，默认关闭。
PROGRESSIVE_PRUNE_INTERVAL=${PROGRESSIVE_PRUNE_INTERVAL:-0}
